services:
  web:
    image: ${DOCKER_IMAGE:-username/406-records:latest}
    ports:
      - "${LISTEN_PORT:-3000}:80"
    environment:
      - POSTMARK_TOKEN=${POSTMARK_TOKEN}
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-https://www.406records.com}
      - TURNSTILE_SECRET=${TURNSTILE_SECRET}
    restart: unless-stopped
